shopping/lcc/urls.py
from django.conf.urls import url
from lcc import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^register/$',views.register,name='register'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^login/$',views.login,name='login'),
    url(r'^detail/(\d+)/$',views.detail,name='detail'),
    url(r'^checkphone/$',views.checkphone,name='checkphone'),
    url(r'^shoppingCart/$',views.shoppingCart,name='shoppingCart'),
    url(r'^addCart/$',views.addCart,name='addCart'),
    url(r'^change/$',views.change,name='change'),
    url(r'^allselect/$',views.allselect,name='allselect'),
    url(r'^delgoods/$',views.delgoods,name='delgoods'),
    url(r'^orderdetail/$',views.orderdetail,name='orderdetail'),
    url(r'^appnotify/$',views.appnotify,name='appnotify'),
    url(r'^returnview/$',views.returnview,name='returnview'),
    url(r'^pay/$',views.pay,name='pay'),
    url(r'^buynow/$',views.buynow,name='buynow'),
]

shopping/shopping/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('lcc.urls',namespace='lcc')),
]

shopping/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>小米商城-永远相信美好的事情即将发生</title>
    <meta name="keyword" content="嗨淘全球,海购,跨境购,代购,进口,跨境电商,海外直邮,化妆品,母婴,奶粉,特卖,免税店,韩流,欧美">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/css/swiper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/js/swiper.min.js"></script>

    <link rel="shortcut icon" href="{% static 'img/xiaomiicon.png' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/basic.css' %}"/>
    <script src="{% static 'js/jquery-1.12.0.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'js/jquery.cookie.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'js/basic.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'js/index.js' %}" type="text/javascript" charset="utf-8"></script>
    <link rel="stylesheet" href="{% static 'css/loop.css' %}">
    <link rel="stylesheet" href="{% static 'css/list.css' %}">

</head>
<body>


<!--头部主体-->
<div class="head_main">
    <!--登录，注册，订单，收藏栏目-->
    <div class="head_main_top">
        <div class="head_main_topM">
            <div class="head_main_topM_left">
                {% if user %}
                    <img id="indeximg" src="{{ user.img }}" alt="">
                    <a href="/logout/">退出</a>
                {% else %}
                    <a href="/login/">登录</a>
                    <a href="/register/">免费注册</a>
                {% endif %}

            </div>
            <div class="head_main_topM_right">

                <a href="/shoppingCart/" style="color: #E10482">我的购物车</a>


            </div>
            <div class="clear"></div>
        </div>
    </div>
    <!--搜索栏-->
    <div class="head_main_middle">
        <div class="head_main_middleM">
            <div class="head_main_middleM_left">
                <a href="#"><img src="{% static 'img/xiaomilogo.png' %}"></a>

            </div>
            <div class="head_main_middleM_right">
                <input type="text" id="input1" placeholder="搜索商品"><input type="button" id="input2" value="搜索">
                <div class="head_main_middleM_rightM">
                    <a href="#">面霜</a><a href="#">|面膜</a><a href="#">|洁面</a><a href="#">|奶粉</a><a href="#">|纸尿裤</a><a
                        href="#">|辅食</a><a href="#">|宝宝营养</a><a href="#">|唇部彩妆</a><a href="#">|身体护理</a><a
                        href="#">|香氛</a>
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <!--导航栏-->
    <div class="head_main_bottom">
        <div class="head_main_bottomM">
            <div class="head_main_bottomM_left">
                <span><a href="{% url 'lcc:index' %}">首页</a></span><span><a href="#list">商品列表</a></span>
            </div>

        </div>
    </div>
</div>
<!--主要内容-->
<div class="concent">
    <!--轮播栏-->
    <div class="concent_top">
        <div class="swiper-container">
            <div class="swiper-wrapper">
                {% for wheel in wheels %}
                    <div class="swiper-slide"><img class="img" src="{{ wheel.img }}" alt=""></div>
                {% endfor %}
            </div>
            <!-- Add Pagination -->
            <div class="swiper-pagination"></div>
            <!-- Add Arrows -->
            <div class="swiper-button-next"></div>
            <div class="swiper-button-prev"></div>
        </div>
    </div>

    <div class="hot_top">
        <div class="hot_topM">
            <a href="#"><img src="{% static 'img/banner0.png' %}"></a>
            <a href="#"><img src="{% static 'img/banner1.png' %}"></a>
            <a href="#"><img src="{% static 'img/banner2.png' %}"></a>
            <a href="#"><img src="{% static 'img/banner3.png' %}"></a>
        </div>
    </div>
    <div class="hot_middle">
        <div class="hot_middleM">
            <div class="hot_middleM_head">
                <img src="{% static 'img/sale.png' %}">
            </div>
            <div class="hot_middleM_main">
                <div class="hot_middleM_main_left">
                    <a href="#"><img src="{% static 'img/hot_top.png' %}"></a>
                </div>
                <div class="hot_middleM_main_right">
                    <a href="#"><img src="{% static 'img/hot_top0.jpg' %}"></a>
                    <a href="#"><img src="{% static 'img/hot_top1.jpg' %}"></a>
                    <a href="#"><img src="{% static 'img/hot_top2.jpg' %}"></a>
                    <a href="#"><img src="{% static 'img/hot_top3.jpg' %}"></a>
                    <a href="#"><img src="{% static 'img/hot_top4.jpg' %}"></a>
                    <a href="#"><img src="{% static 'img/hot_top5.jpg' %}"></a>
                </div>
                <div class="clear">

                </div>
            </div>
        </div>
    </div>
    <div class="hot_bottom">
        <div class="hot_bottomM">
            <div class="hot_bottomM_head">
                <img src="{% static 'img/sale1.png' %}">
            </div>
            <div class="hot_bottomM_main">
                <div class="hot_bottomM_main_left">
                    <a href="#"><img src="{% static 'img/hot_bottom.png' %}"></a>
                </div>
                <div class="hot_bottomM_main_right">
                    <a href="#"><img src="{% static 'img/hot_bottom0.jpg' %}"></a>
                    <a href="#"><img src="{% static 'img/hot_bottom1.jpg' %}"></a>
                    <a href="#"><img src="{% static 'img/hot_bottom2.jpg' %}"></a>
                    <a href="#"><img src="{% static 'img/hot_bottom3.jpg' %}"></a>
                </div>
                <div class="clear">

                </div>
            </div>
        </div>
    </div>
</div>
<!--列表-->
<div id="list">
    <div class="listM">
        <div class="listM_left">
            <div class="listM_left_head">
                <img src="{% static 'img/list.png' %}">
                <a href="#">查看更多&nbsp;&gt;</a>
            </div>
        </div>
        <div class="list_left">
            <div class="list_left_top">
                <img src="{% static 'img/hot_top.png' %}" alt="">
                {% for computer in computers %}
                    <a href="{% url 'lcc:detail' computer.id%}"><img class="picture" src="{{ computer.img }}" alt=""></a>
                {% endfor %}

            </div>
        </div>
        <div class="listM_right">
            <div class="listM_right_top">
                <h2>------------&nbsp;&nbsp;热销品牌&nbsp;&nbsp;------------</h2>
                <div class="listM_right_top_img">
                    <a href="#"><img src="{% static 'img/sidebar0.jpg' %}">
                        <p>Lancome/兰蔻</p></a>
                    <a href="#"><img src="{% static 'img/sidebar1.jpg' %}">
                        <p>倩碧</p></a>
                    <a href="#"><img src="{% static 'img/sidebar2.jpg' %}">
                        <p>Origins/悦木之源</p></a>
                    <a href="#"><img src="{% static 'img/sidebar3.jpg' %}">
                        <p>箭牌</p></a>
                    <a href="#"><img src="{% static 'img/sidebar4.jpg' %}">
                        <p>施华蔻</p></a>
                    <a href="#"><img src="{% static 'img/sidebar5.jpg' %}">
                        <p>za</p></a>
                    <a href="#"><img src="{% static 'img/sidebar6.jpg' %}">
                        <p>innisfree/悦诗风吟</p></a>
                    <a href="#"><img src="{% static 'img/sidebar7.jpg' %}">
                        <p>梦妆</p></a>
                    <a href="#"><img src="{% static 'img/sidebar8.jpg' %}">
                        <p>Dr.g</p></a>
                    <a href="#"><img src="{% static 'img/sidebar9.jpg' %}">
                        <p>Aveeno/艾维诺</p></a>
                    <a href="#"><img src="{% static 'img/sidebar10.jpg' %}">
                        <p>新安怡</p></a>
                    <a href="#"><img src="{% static 'img/sidebar11.jpg' %}">
                        <p>boon</p></a>
                    <div class="clear">

                    </div>
                </div>
            </div>
            <div class="listM_right_bottom">
                <h2>------------&nbsp;&nbsp;精选专题&nbsp;&nbsp;------------</h2>
                <div class="listM_right_bottom_img">
                    <a href="#"><img src="{% static 'img/sidebar_choice0.jpg' %}"></a>
                    <a href="#"><img src="{% static 'img/sidebar_choice1.jpg' %}"></a>
                </div>

            </div>
        </div>
        <div class="clear">

        </div>
    </div>
</div>
<!--尾部-->
<div class="foot">
    <div class="foot_top">
        <div class="foot_topM">
            <div class="foot_topM_left">
                <dl>
                    <dt>新手指南</dt>
                    <a href="#">
                        <dd>购物流程</dd>
                    </a>
                    <a href="#">
                        <dd>购物须知</dd>
                    </a>
                    <a href="#">
                        <dd>联系客服</dd>
                    </a>
                    <a href="#">
                        <dd>常见问题</dd>
                    </a>
                </dl>
                <dl>
                    <dt>支付方式</dt>
                    <a href="#">
                        <dd>第三方平台支付</dd>
                    </a>
                    <a href="#">
                        <dd>优惠券使用</dd>
                    </a>
                </dl>
                <dl>
                    <dt>售后服务</dt>
                    <a href="#">
                        <dd>退款政策</dd>
                    </a>
                    <a href="#">
                        <dd>退款流程</dd>
                    </a>
                    <a href="#">
                        <dd>退款说明</dd>
                    </a>
                </dl>
                <dl>
                    <dt>商品配送</dt>
                    <a href="#">
                        <dd>运费说明</dd>
                    </a>
                    <a href="#">
                        <dd>配送范围</dd>
                    </a>
                    <a href="#">
                        <dd>发货说明</dd>
                    </a>
                    <a href="#">
                        <dd>物流查询</dd>
                    </a>
                </dl>
                <dl>
                    <dt>品牌保证</dt>
                    <a href="#">
                        <dd>官方授权</dd>
                    </a>
                    <a href="#">
                        <dd>海关监管</dd>
                    </a>
                    <a href="#">
                        <dd>免税包邮</dd>
                    </a>
                    <a href="#">
                        <dd>售后无忧</dd>
                    </a>
                </dl>
                <dl>
                    <dt>手机嗨淘全球</dt>
                    <dd class="last_dd"><img src="{% static 'img/foot.png' %}"></dd>
                </dl>
                <div class="clear">

                </div>
            </div>
        </div>
    </div>
    <div class="foot_middle">
        <div class="foot_middleM">
            <div class="foot_middleM_left">
                <span><img src="{% static 'img/dianhua.png' %}"></span>
                <span>4008-006-006</span>
            </div>
            <div class="foot_middleM_right">
                <ul>
                    <li><a href="#">公司简介</a></li>
                    <li><a href="#">联系我们</a></li>
                    <li><a href="#">大事记</a></li>
                    <li><a href="#">人才招募</a></li>
                    <li><a href="#">帮助中心</a></li>
                    <li><a href="#">法律说明</a></li>
                    <li><a href="#">合作专区</a></li>
                    <li><a href="#">友情链接</a></li>
                </ul>
            </div>
            <div class="clear">

            </div>
        </div>
    </div>
    <div class="foot_bottom">
        <div class="foot_bottomM">
            <div class="foot_bottomM_top">
                <p>Copyright © 2010 - 2016, 版权所有 HITAO.TOP 湘ICP备10012668号-3 嗨淘全球网　|　<a href="#">营业执照</a></p>
            </div>
            <div class="foot_bottomM_right">
                <a href="#"><img src="{% static 'img/foot0.png' %}"></a>
                <a href="#"><img src="{% static 'img/foot1.png' %}"></a>
                <a href="#"><img src="{% static 'img/foot2.png' %}"></a>
                <a href="#"><img src="{% static 'img/foot3.png' %}"></a>
                <a href="#"><img src="{% static 'img/foot4.png' %}"></a>
            </div>
        </div>
    </div>
</div>
<!--右边侧栏-->

<script src="{% static 'js/loop.js' %}"></script>

</body>
</html>

shopping/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>嗨淘全球购登录页面</title>
    <script src="{% static 'js/jquery-1.12.0.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'js/login.js'%}" type="text/javascript" charset="utf-8"></script>
</head>
<body>
    <form action="{% url 'lcc:login' %}" method="post">
        {% csrf_token %}
        手机号：<input id="phone" type="text" name="phone" placeholder="请输入手机号" maxlength="11">
        <span style="color: red;font-size: 12px"></span>
        <p></p>
        密码：<input type="password" name="password" placeholder="请输入密码" maxlength="20">
        <p style="color: red;font-size: 12px">
        {% if err %}
            {{ err }}
        {% endif %}</p>
        <input type="submit" value="登录">

    </form>
</body>
</html>

shopping/templates/orderdetail.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>小米商城 - 购物车</title>
        <link rel="shortcut icon" href="{% static 'img/xiaomiicon.png' %}"/>
		<script src="{% static 'js/jquery-1.12.0.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'js/jquery.cookie.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'js/basic.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'js/orderdetail.js' %}" type="text/javascript" charset="utf-8"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'css/basic.css' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static 'css/shoppingCart.css' %}"/>
	</head>
	<body>
		<!--头部主体-->
		<div class="head_main"> 
			<!--登录，注册，订单，收藏栏目-->
			<div class="head_main_top">
				<div class="head_main_topM">
					<div class="head_main_topM_left">
						{% if user %}
                            <img id="indeximg" src="{{ user.img }}" alt="">
                            <a href="/logout/">退出</a>
                        {% else %}
                            <a href="/login/">登录</a>
                            <a href="/register/">免费注册</a>
                        {% endif %}
					</div>
					<div class="head_main_topM_right">

					</div>
					<div class="clear"></div>
				</div>
			</div>
			<!--搜索栏-->
			<div class="head_main_middle">
				<div class="head_main_middleM">
					<div class="head_main_middleM_left">
						<a href="{% url 'lcc:index' %}"><img src="{% static 'img/xiaomilogo.png' %}"/></a>

					</div>
					<div class="head_main_middleM_right">
						<input type="text"id="input1" placeholder="搜索商品"/><input type="button"  id="input2" value="搜索" />
						<div class="head_main_middleM_rightM">
							<a href="#">面霜</a><a href="#">|面膜</a><a href="#">|洁面</a><a href="#">|奶粉</a><a href="#">|纸尿裤</a><a href="#">|辅食</a><a href="#">|宝宝营养</a><a href="#">|唇部彩妆</a><a href="#">|身体护理</a><a href="#">|香氛</a>
						</div>
					</div>
					<div class="clear"></div>
				</div>
			</div>
		</div>
		<div class="ware">
			<div class="wareM">
				<div class="wareM1">
					<span>1.购物袋</span>
					<span style="color: #E10482">2.确认订单信息</span>
					<span>3.付款</span>
				</div>
				<div class="wareM2">

					<span class="one">商品</span>
					<span class="twe">单价</span>
					<span class="three">数量</span>
					<span class="three">小计</span>
					<span class="three">操作</span>
				</div>
				<!--加载-->
                <div class="detailcart">

                    {% for cart in carts %}

                        {% if cart.isselect %}
                            <div class="onegoods">
                                <div class="product">
                                    <div class="picture"><img src="{{ cart.computers.img1 }}" alt=""></div>
                                    <div class="infomation"><p>{{ cart.computers.title }}</p></div>
                                </div>
                                <div class="price">{{ cart.computers.price }}</div>
                                <div class="number"><span>{{ cart.number }}</span></div>
                                <div class="subtotal"></div>
                                <div class="options" computersid="{{ cart.computers.id }}"><p>删除</p></div>
                            </div>
                        {% endif %}

                    {% endfor %}

                </div>
				<!--加载结束-->
				<div class="clear">
					
				</div>

				<div class="wareM6">

					<div class="wareM6_right">
						<div class="btn"><button id="pay" identifier="{{ identifier }}">去付款</button></div>
						<div class="wareM6_right_p">
							<p>合计（不含运费及税费）<em>￥</em><span class="s1"></span></p>
						</div>
						<div class="clear">
							
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--尾部-->
		<div class="foot">
			<div class="foot_middle">
				<div class="foot_middleM">
					<div class="foot_middleM_left">
						<span><img src="{% static 'img/dianhua.png' %}"/></span>
						<span>4008-006-006</span>
					</div>
					<div class="foot_middleM_right">
						<ul>
							<li><a href="#">公司简介</a></li>
							<li><a href="#">联系我们</a></li>
							<li><a href="#">大事记</a></li>
							<li><a href="#">人才招募</a></li>
							<li><a href="#">帮助中心</a></li>
							<li><a href="#">法律说明</a></li>
							<li><a href="#">合作专区</a></li>
							<li><a href="#">友情链接</a></li>
						</ul>
					</div>
					<div class="clear">
						
					</div>
				</div>
			</div>
			<div class="foot_bottom">
				<div class="foot_bottomM">
					<div class="foot_bottomM_top">
						<p>Copyright © 2010 - 2016, 版权所有 HITAO.TOP    湘ICP备10012668号-3  嗨淘全球网　|　<a href="#">营业执照</a></p>
					</div>
					<div class="foot_bottomM_right">
						<a href="#"><img src="{% static 'img/foot0.png' %}"/></a>
						<a href="#"><img src="{% static 'img/foot1.png' %}"/></a>
						<a href="#"><img src="{% static 'img/foot2.png' %}"/></a>
						<a href="#"><img src="{% static 'img/foot3.png' %}"/></a>
						<a href="#"><img src="{% static 'img/foot4.png' %}"/></a>
					</div>
				</div>
			</div>
		</div>
		<!--右边侧栏-->

	</body>
</html>

shopping/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>嗨淘全球购注册页面</title>
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
    <script src="{% static 'js/jquery-1.12.0.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'js/register.js'%}" type="text/javascript" charset="utf-8"></script>
</head>
<body>
    <h3>欢迎注册加入米粉大军</h3>
    <h3>自己人？<a href="/login/">去登陆</a></h3>
    <form id="register" action="{% url 'lcc:register' %}" method="post">
        {% csrf_token %}
        手机号：<input id="phone" type="text" name="phone" placeholder="请输入手机号" maxlength="11">
        <span></span>
        <span style="font-size: 12px;color: green"></span>
        <p></p>
        密码：<input type="password" name="password" placeholder="请输入6位密码" maxlength="6" id="passwd">
        <span></span>
        <p class="prompt"></p>
        <div id="subbtn">注册</div>
    </form>


</body>
</html>

shopping/templates/shoppingCart.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>小米商城 - 购物车</title>
        <link rel="shortcut icon" href="{% static 'img/xiaomiicon.png' %}"/>
		<script src="{% static 'js/jquery-1.12.0.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'js/jquery.cookie.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'js/basic.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'js/shoppingCart.js' %}" type="text/javascript" charset="utf-8"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'css/basic.css' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static 'css/shoppingCart.css' %}"/>
	</head>
	<body>
		<!--头部主体-->
		<div class="head_main"> 
			<!--登录，注册，订单，收藏栏目-->
			<div class="head_main_top">
				<div class="head_main_topM">
					<div class="head_main_topM_left">
						{% if user %}
                            <img id="indeximg" src="{{ user.img }}" alt="">
                            <a href="/logout/">退出</a>
                        {% else %}
                            <a href="/login/">登录</a>
                            <a href="/register/">免费注册</a>
                        {% endif %}
					</div>
					<div class="head_main_topM_right">

					</div>
					<div class="clear"></div>
				</div>
			</div>
			<!--搜索栏-->
			<div class="head_main_middle">
				<div class="head_main_middleM">
					<div class="head_main_middleM_left">
						<a href="{% url 'lcc:index' %}"><img src="{% static 'img/xiaomilogo.png' %}"/></a>

					</div>
					<div class="head_main_middleM_right">
						<input type="text"id="input1" placeholder="搜索商品"/><input type="button"  id="input2" value="搜索" />
						<div class="head_main_middleM_rightM">
							<a href="#">面霜</a><a href="#">|面膜</a><a href="#">|洁面</a><a href="#">|奶粉</a><a href="#">|纸尿裤</a><a href="#">|辅食</a><a href="#">|宝宝营养</a><a href="#">|唇部彩妆</a><a href="#">|身体护理</a><a href="#">|香氛</a>
						</div>
					</div>
					<div class="clear"></div>
				</div>
			</div>
		</div>
		<div class="ware">
			<div class="wareM">
				<div class="wareM1">
					<span style="color: #E10482">1.购物袋</span>
					<span>2.确认订单信息</span>
					<span>3.付款</span>
				</div>
				<div class="wareM2">
					<div class="wareM2_left">
						<input type="checkbox"  id="quanxuan" checked/>
						<b>全选</b>
					</div>
					<span class="one">商品</span>
					<span class="twe">单价</span>
					<span class="three">数量</span>
					<span class="three">小计</span>
					<span class="three">操作</span>
				</div>
				<!--加载-->
                <div class="detailcart">
                    {% if carts %}
                        {% for cart in carts %}

                            <div class="onegoods">
                                <div class="leftbox"><input type="checkbox"  class="danxuan" value="{{ cart.computers.id }}" checked/></div>
                                <div class="product">
                                    <div class="picture"><img src="{{ cart.computers.img1 }}" alt=""></div>
                                    <div class="infomation"><p>{{ cart.computers.title }}</p></div>
                                </div>
                                <div class="price">{{ cart.computers.price }}</div>
                                <div class="number"><span>{{ cart.number }}</span></div>
                                <div class="subtotal"></div>
                                <div class="options" computersid="{{ cart.computers.id }}"><p>删除</p></div>
                            </div>

                        {% endfor %}
                    {% else %}
                        <p>购物车空空如也，快去选购商品吧亲！<a href="/#list">去选购</a></p>
                    {% endif %}
                </div>
				<!--加载结束-->
				<div class="clear">
					
				</div>

				<div class="wareM6">

					<div class="wareM6_right">
                        <div class="btn"><a href="/orderdetail/"><button>去下单</button></a></div>
						<div class="wareM6_right_p">
							<p>已选<span class="selectnum"></span>件商品，合计（不含运费及税费）<em>￥</em><span class="s1"></span></p>
						</div>
						<div class="clear">
							
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--尾部-->
		<div class="foot">
			<div class="foot_middle">
				<div class="foot_middleM">
					<div class="foot_middleM_left">
						<span><img src="{% static 'img/dianhua.png' %}"/></span>
						<span>4008-006-006</span>
					</div>
					<div class="foot_middleM_right">
						<ul>
							<li><a href="#">公司简介</a></li>
							<li><a href="#">联系我们</a></li>
							<li><a href="#">大事记</a></li>
							<li><a href="#">人才招募</a></li>
							<li><a href="#">帮助中心</a></li>
							<li><a href="#">法律说明</a></li>
							<li><a href="#">合作专区</a></li>
							<li><a href="#">友情链接</a></li>
						</ul>
					</div>
					<div class="clear">
						
					</div>
				</div>
			</div>
			<div class="foot_bottom">
				<div class="foot_bottomM">
					<div class="foot_bottomM_top">
						<p>Copyright © 2010 - 2016, 版权所有 HITAO.TOP    湘ICP备10012668号-3  嗨淘全球网　|　<a href="#">营业执照</a></p>
					</div>
					<div class="foot_bottomM_right">
						<a href="#"><img src="{% static 'img/foot0.png' %}"/></a>
						<a href="#"><img src="{% static 'img/foot1.png' %}"/></a>
						<a href="#"><img src="{% static 'img/foot2.png' %}"/></a>
						<a href="#"><img src="{% static 'img/foot3.png' %}"/></a>
						<a href="#"><img src="{% static 'img/foot4.png' %}"/></a>
					</div>
				</div>
			</div>
		</div>
		<!--右边侧栏-->

	</body>
</html>